AUDIO_DIR = './voxceleb/voxceleb1_wav'

#NUM_FRAMES = 23
#NUM_PREVIOUS_FRAME = 13
NUM_PREVIOUS_FRAME = 9
NUM_NEXT_FRAME = 23
NUM_FRAMES = NUM_PREVIOUS_FRAME + NUM_NEXT_FRAME

USE_DELTA = 0
SAMPLE_RATE = 16000
TRUNCATE_SOUND_FIRST_SECONDS = 0.5
FILTER_BANK = 64

