DATASET_DIR = '../Data/dataset/'
AUDIO_DIR = '../Data/dataset/'

# The length of shortest wav
N_SAMPLES = 800
MINIMUIN_LENGTH = 400

# Parameters for fbank features
NUM_PREVIOUS_FRAME = 9
#NUM_PREVIOUS_FRAME = 13
NUM_NEXT_FRAME = 23

NUM_FRAMES = NUM_PREVIOUS_FRAME + NUM_NEXT_FRAME
USE_LOGSCALE = True
USE_DELTA = False
USE_SCALE = True
USE_ENERGY = False
SAMPLE_RATE = 16000
TRUNCATE_SOUND_FIRST_SECONDS = 0.5
FILTER_BANK = 64

TDNN_FBANK_FILTER = 23
CMVN = 'cmvnw'
VAD = True
NORMALIZE = True

# Paramters for Spectrogram
NUM_FFT = 512
NUM_FRAMES_SPECT = 300

# Parameters for VAD
VAD_ENERGY_THRESHOLD = 5.5
VAD_ENERGY_MEAN_SCALE = 0.5
VAD_PROPORTION_THRESHOLD = 0.12
VAD_FRAMES_CONTEXT = 2

