DATASET_DIR = '../Data/dataset/'
AUDIO_DIR = '../Data/dataset/'


# Parameters for fbank features
NUM_PREVIOUS_FRAME = 9
#NUM_PREVIOUS_FRAME = 13
NUM_NEXT_FRAME = 23

NUM_FRAMES = NUM_PREVIOUS_FRAME + NUM_NEXT_FRAME
USE_LOGSCALE = True
USE_DELTA = False
USE_SCALE = False
SAMPLE_RATE = 16000
TRUNCATE_SOUND_FIRST_SECONDS = 0.5
FILTER_BANK = 64
TDNN_FBANK_FILTER = 24

# Paramters for Spectrogram
NUM_FFT = 512

NUM_PREVIOUS_FRAME_SPECT = 100
NUM_NEXT_FRAME_SPECT = 150
NUM_FRAMES_SPECT = NUM_PREVIOUS_FRAME_SPECT + NUM_NEXT_FRAME_SPECT

